twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_url: '%env(APP_URL)%'
        website_url: '%env(WEBSITE_URL)%' 
        gg_recaptcha_site_key: '%env(GOOGLE_CAPTCHA_SITE_KEY)%' 

when@test:
    twig:
        strict_variables: true